"""nullable fix for some fields

Revision ID: 53cfd9da4437
Revises: 9118a7104498
Create Date: 2020-12-10 13:05:26.306217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cfd9da4437'
down_revision = '9118a7104498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sum_of_money', sa.Float(), nullable=False),
    sa.Column('transactions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transactions_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('wallet')
    op.drop_table('transactions')
    op.drop_table('token')
    # ### end Alembic commands ###
